config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present? && !EXCLUDED_SUBDOMAINS.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    devise_for :users
  end

  root to: "welcome#index"
  resources :accounts

  get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: SUBDOMAIN_REGEX, message: 'contains invalid characters' },
                        exclusion: { in: EXCLUDED_SUBDOMAINS, message: 'restricted' }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

  private
  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
         ##:trackable, :registerable

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  attr_reader :account

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      sign_in(account.owner)
      flash[:notice] = "Signed up successfully"
      redirect_to root_path
    else
      render action: 'new'
    end
  end

  private
  def account_params
    params.require(:account).permit(:subdomain, owner_attributes: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from Exception, with: :not_found
  rescue_from ActionController::RoutingError, with: :not_found

  def raise_not_found
    raise ActionController::RoutingError.new("No route matches #{params[:unmatched_route]}")
  end

  def not_found
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end

  def error
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/500", :layout => false, :status => :error }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper

  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        name = (name.to_s == 'notice') ? 'success' : 'danger'
        flash_message = %Q(
                           <div class="alert alert-#{name}">
                             <a class="close" data-dismiss="alert">&#215;</a>
                               <div id="flash_#{name}">#{msg}</div>
                           </div>
                          )
        concat flash_message.html_safe
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
      <h2>Create an Account</h2>

      <%= form_for @account do |f| %>
        <%= f.fields_for :owner do |own| %>
          <%= form_group_for own, :name do %>
            <%= own.text_field :name, class: 'form-control' %>
          <% end %>
          <%= form_group_for own, :email do %>
            <%= own.text_field :email, class: 'form-control' %>
          <% end %>
          <%= form_group_for own, :password do %>
            <%= own.password_field :password, class: 'form-control' %>
          <% end %>
          <%= form_group_for own, :password_confirmation do %>
            <%= own.password_field :password_confirmation, class: 'form-control' %>
          <% end %>
        <% end %>

        <%= form_group_for f, :subdomain do %>
          <div class="input-group">
            <%= f.text_field :subdomain, class: 'form-control' %>
            <span class="input-group-addon">.demoapp.dev</span>
          </div>
        <% end %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo-App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'shared/navigation_bar' %>

    <div class="container">
      <%= flash_messages if show_layout_flash? %>
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Demo-App', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <div class="pull-right right-buttons">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <h1>Demo-App</h1>
    <p>Put your fancy, smancy, one liner here if you like.</p>
    <p><%= link_to "Create Account", new_account_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
</div>